/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "hi" | "kn" | "te" | "ta" | "mr";

export const translations = {
  en: {
    title: "HERITAGE MATRIMONY",
    subtitle: "Sacred Lineage • Brahmin Alliance",
    matches: "Matches",
    compatibility: "Compatibility",
    chat: "Chat",
    videoCall: "Video Call",
    vendorsHub: "Online Store",
    verifyHub: "Verify Hub",
    selfAudit: "Self Audit",
    font: "Font",
    verifyId: "Verify ID",
    aadhaarVerified: "Aadhaar Verified",
    memberView: "Member View",
    superAdmin: "Super Admin",
    moderator: "Moderator",
    support: "Support",
    traditionalFilters: "Traditional Matrimonial Filters",
    traditionalFiltersDesc: "Refine matches based on ancestral lineage and star alignments.",
    allGenders: "All Genders",
    allBrahminSects: "All Brahmin Sects",
    allAncestralGotras: "All Ancestral Gotras",
    seekingMen: "Seeking Men (Female)",
    seekingWomen: "Seeking Women (Male)",
    shubhVivaah: "Shubh Vivaah & Gotra Sanctity",
    agraharamUnion: "Auspicious Agraharam Union",
    bannerDesc: "Welcome to Heritage Matrimony, strictly curated for global Brahmin clans. Validate sacred gotra compatibility, matched with Google Gemini's traditional chart analysis, and unlock certified identity dossiers.",
    verifiedSects: "Verified Sects",
    gotraIntegrity: "Gotra Integrity",
    secure100: "100% Secure",
    adminDeck: "Admin Control & Mock-Test Deck",
    adminDeckDesc: "Instantly verify platform features, simulate matches, and perform real-time profile injections/deletions.",
    addNewProfile: "Add New Mock Profile",
    totalProfiles: "TOTAL PROFILES",
    verifiedByAadhaar: "VERIFIED BY AADHAAR",
    sagotraCompliant: "SAGOTRA COMPLIANT",
    activated: "Activated",
    modTesting: "MOD TESTING CAPACITY",
    differentRules: "Different Authorization Rules:",
    rulesDesc: "Super Admin has absolute rights to delete any profile and run database stresses. Moderator can verify/add matches but lacks deletion rights. Support view is read-only. Standard Members cannot see this dashboard or the Self Audit tab.",
    age: "Age",
    gender: "Gender",
    gotra: "Gotra",
    sect: "Sect",
    nakshatra: "Nakshatra",
    rasi: "Moon Rasi",
    lagnam: "Birth Lagnam",
    occupation: "Occupation",
    location: "Location",
    education: "Education",
    bio: "Bio",
    expectations: "Expectations",
    achievements: "Achievements",
    familyWishes: "Family Wishes",
    viewHoroscope: "View Horoscope Chart",
    hideHoroscope: "Hide Horoscope Chart",
    compatCalculator: "Calculate Gemini Match",
    startEncryptedChat: "Start Encrypted Chat",
    aadhaarStatus: "Aadhaar Match Score",
    unverified: "Unverified",
    verified: "Verified",
    yes: "Yes",
    no: "No",
    chevvaiDosham: "Chevvai Dosham",
    rahuKetuDosham: "Rahu Ketu Dosham",
    backToMatches: "Back to Matches",
    compatibilityChartTitle: "Traditional Kundali Astro Alignment",
    compatibilityChartDesc: "Vedic matching values computed alongside Gemini compatibility insight checks.",
    lifestyleHarmony: "Lifestyle Harmony",
    coreValuesAlign: "Core Values Alignment",
    careerSynergy: "Career Synergy",
    emotionalConnect: "Emotional Connect",
    overallScore: "Overall Score",
    geminiInsight: "Gemini Match Insight",
    secureChatTitle: "Secure Peer-to-Peer Chat",
    secureChatDesc: "End-to-End Cryptographic Match Shield",
    ciphertext: "Ciphertext",
    decryptedText: "Decrypted Text",
    typeAMessage: "Type a secure message...",
    send: "Send",
    sacredVirtualMeeting: "Sacred Virtual Meeting",
    meetingDesc: "Auspicious face-to-face family interaction powered by peer-to-peer connection.",
    p2pStatus: "P2P Cryptographic Connection Status",
    startSafeCall: "Start Safe Call",
    disconnectCall: "Disconnect Call",
    kalyanaVendors: "Auspicious Wedding Vendors",
    vendorsDesc: "Sattvik Caterers, Purohits, Kalyana Mandapams, and Vedic Astrologers.",
    bookNow: "Book Now",
    rating: "Rating",
    pricing: "Pricing",
    contactPerson: "Contact Person",
    verificationDesk: "Brahmin Verification Desk",
    verificationDesc: "Audit, verify, and validate Aadhaar and cosmological credentials.",
    auditLog: "Vedic Platform Audit Log",
    auditLogDesc: "Real-time logs for system stresses, user authorization changes, and credential logins.",
  },
  hi: {
    title: "HERITAGE MATRIMONY",
    subtitle: "पवित्र वंश • ब्राह्मण गठबंधन",
    matches: "योग्य वर-वधू",
    compatibility: "कुंडली मिलान",
    chat: "सुरक्षित चैट",
    videoCall: "वीडियो कॉल",
    vendorsHub: "ऑनलाइन स्टोर",
    verifyHub: "सत्यापन केंद्र",
    selfAudit: "सिस्टम ऑडिट",
    font: "अक्षर आकार",
    verifyId: "पहचान सत्यापित करें",
    aadhaarVerified: "आधार सत्यापित",
    memberView: "सदस्य दृश्य",
    superAdmin: "मुख्य व्यवस्थापक",
    moderator: "मध्यस्थ",
    support: "सहायता",
    traditionalFilters: "पारंपरिक वैवाहिक फ़िल्टर",
    traditionalFiltersDesc: "पूर्वजों के गोत्र और नक्षत्रों के आधार पर खोजें।",
    allGenders: "सभी लिंग",
    allBrahminSects: "सभी संप्रदाय",
    allAncestralGotras: "सभी गोत्र",
    seekingMen: "वर की तलाश (कन्या)",
    seekingWomen: "वधू की तलाश (वर)",
    shubhVivaah: "शुभ विवाह और गोत्र पवित्रता",
    agraharamUnion: "मंगल अग्रहारम मिलान",
    bannerDesc: "धरोहर वैवाहिक में आपका स्वागत है, जो विशेष रूप से ब्राह्मण परिवारों के लिए है। पवित्र गोत्र अनुकूलता, जेमिनी कुंडली विश्लेषण और सत्यापित आधार रिकॉर्ड की जांच करें।",
    verifiedSects: "सत्यापित संप्रदाय",
    gotraIntegrity: "गोत्र अखंडता",
    secure100: "100% सुरक्षित",
    adminDeck: "व्यवस्थापक नियंत्रण पैनल",
    adminDeckDesc: "सिस्टम सुविधाओं का परीक्षण करें, नए नकली प्रोफाइल जोड़ें या हटाएं।",
    addNewProfile: "नया मॉक प्रोफाइल जोड़ें",
    totalProfiles: "कुल प्रोफाइल",
    verifiedByAadhaar: "आधार सत्यापित प्रोफाइल",
    sagotraCompliant: "सगोत्र निषेध",
    activated: "सक्रिय है",
    modTesting: "परीक्षण क्षमता",
    differentRules: "अधिकार नियम:",
    rulesDesc: "मुख्य व्यवस्थापक के पास प्रोफाइल हटाने का पूर्ण अधिकार है। मध्यस्थ केवल प्रोफाइल जोड़ सकते हैं।",
    age: "आयु",
    gender: "लिंग",
    gotra: "गोत्र",
    sect: "संप्रदाय",
    nakshatra: "नक्षत्र",
    rasi: "चंद्र राशि",
    lagnam: "जन्म लग्न",
    occupation: "व्यवसाय",
    location: "स्थान",
    education: "शिक्षा",
    bio: "परिचय",
    expectations: "अपेक्षाएं",
    achievements: "उपलब्धियां",
    familyWishes: "पारिवारिक इच्छाएं",
    viewHoroscope: "कुंडली चार्ट देखें",
    hideHoroscope: "कुंडली छिपाएं",
    compatCalculator: "जेमिनी कुंडली मिलान करें",
    startEncryptedChat: "सुरक्षित चैट शुरू करें",
    aadhaarStatus: "आधार मिलान स्कोर",
    unverified: "अपुष्ट",
    verified: "सत्यापित",
    yes: "हाँ",
    no: "नहीं",
    chevvaiDosham: "मांगलिक दोष",
    rahuKetuDosham: "राहु-केतु दोष",
    backToMatches: "वापस प्रोफाइल पर जाएं",
    compatibilityChartTitle: "पारंपरिक अष्टकूट कुंडली मिलान",
    compatibilityChartDesc: "वैदिक गणनाओं और जेमिनी एआई विश्लेषण पर आधारित मिलान।",
    lifestyleHarmony: "जीवनशैली सद्भाव",
    coreValuesAlign: "मूल विचार मिलान",
    careerSynergy: "करियर अनुकूलता",
    emotionalConnect: "भावनात्मक जुड़ाव",
    overallScore: "कुल अंक",
    geminiInsight: "जेमिनी एआई का मिलान निष्कर्ष",
    secureChatTitle: "सुरक्षित पीयर-टू-पीयर चैट",
    secureChatDesc: "पूर्ण सुरक्षित कूटबद्ध चैट कवच",
    ciphertext: "कूटबद्ध संदेश (सुरक्षित)",
    decryptedText: "पठनीय संदेश",
    typeAMessage: "सुरक्षित संदेश टाइप करें...",
    send: "भेजें",
    sacredVirtualMeeting: "पवित्र वर्चुअल मिलन",
    meetingDesc: "सुरक्षित और कूटबद्ध वीडियो वार्तालाप द्वारा आमने-सामने पारिवारिक मिलन।",
    p2pStatus: "कनेक्शन स्थिति",
    startSafeCall: "कॉल शुरू करें",
    disconnectCall: "कॉल काटें",
    kalyanaVendors: "पवित्र विवाह वेंडर्स",
    vendorsDesc: "सात्विक कैटरर्स, पूजनीय पुरोहित, मांगलिक कल्याण मंडपम और वैदिक ज्योतिषी।",
    bookNow: "अभी बुक करें",
    rating: "रेटिंग",
    pricing: "मूल्य निर्धारण",
    contactPerson: "संपर्क व्यक्ति",
    verificationDesk: "ब्राह्मण सत्यापन डेस्क",
    verificationDesc: "आधार विवरण और कुंडली प्रमाण पत्रों का सत्यापन जांच।",
    auditLog: "वैदिक प्लेटफ़ॉर्म लॉग",
    auditLogDesc: "सुरक्षा जांच, क्रेडेंशियल लॉगिन और व्यवस्थापक परिवर्तनों के रीयल-टाइम रिकॉर्ड।",
  },
  kn: {
    title: "HERITAGE MATRIMONY",
    subtitle: "ಪವಿತ್ರ ವಂಶಾವಳಿ • ಬ್ರಾಹ್ಮಣ ಮೈತ್ರಿ",
    matches: "ವರ-ವಧುಗಳು",
    compatibility: "ಜಾತಕ ಹೊಂದಾಣಿಕೆ",
    chat: "ಸುರಕ್ಷಿತ ಚಾಟ್",
    videoCall: "ವೀಡಿಯೊ ಕರೆ",
    vendorsHub: "ಆನ್‌ಲೈನ್ ಸ್ಟೋರ್",
    verifyHub: "ವೆರಿಫಿಕೇಶನ್ ಹಬ್",
    selfAudit: "ಸಿಸ್ಟಮ್ ಆಡಿಟ್",
    font: "ಅಕ್ಷರ ಗಾತ್ರ",
    verifyId: "ವೆರಿಫೈ ಐಡಿ",
    aadhaarVerified: "ಆಧಾರ್ ವೆರಿಫೈಡ್",
    memberView: "ಸದಸ್ಯರ ನೋಟ",
    superAdmin: "ಸೂಪರ್ ಅಡ್ಮಿನ್",
    moderator: "ಮಾಡರೇಟರ್",
    support: "ಸಪೋರ್ಟ್",
    traditionalFilters: "ಸಾಂಪ್ರದಾಯಿಕ ಫಿಲ್ಟರ್‌ಗಳು",
    traditionalFiltersDesc: "ಗೋತ್ರ, ಜನ್ಮ ನಕ್ಷತ್ರ ಹಾಗೂ ರಾಶಿಯ ಆಧಾರದ ಮೇಲೆ ಹುಡುಕಾಟ ನಡೆಸಿ.",
    allGenders: "ಎಲ್ಲಾ ಲಿಂಗಗಳು",
    allBrahminSects: "ಎಲ್ಲಾ ಬ್ರಾಹ್ಮಣ ಪಂಗಡಗಳು",
    allAncestralGotras: "ಎಲ್ಲಾ ಗೋತ್ರಗಳು",
    seekingMen: "ವರನ ಹುಡುಕಾಟ (ವಧು)",
    seekingWomen: "ವಧುವಿನ ಹುಡುಕಾಟ (ವರ)",
    shubhVivaah: "ಶುಭ ವಿವಾಹ ಮತ್ತು ಗೋತ್ರ ಪವಿತ್ರತೆ",
    agraharamUnion: "ಮಂಗಳಕರ ಅಗ್ರಹಾರ ಒಕ್ಕೂಟ",
    bannerDesc: "ಬ್ರಾಹ್ಮಣ ಸಮಾಜಕ್ಕಾಗಿ ಪ್ರತ್ಯೇಕವಾಗಿ ಸಿದ್ಧಪಡಿಸಲಾದ ಪರಂಪರೆ ಮ್ಯಾಟ್ರಿಮೋನಿಗೆ ಸ್ವಾಗತ. ಗೋತ್ರ ಹೊಂದಾಣಿಕೆ ಮತ್ತು ಜಾತಕ ವಿಶ್ಲೇಷಣೆ ವೀಕ್ಷಿಸಿ.",
    verifiedSects: "ವೆರಿಫೈಡ್ ಪಂಗಡಗಳು",
    gotraIntegrity: "ಗೋತ್ರ ನಿಷ್ಠೆ",
    secure100: "100% ಸುರಕ್ಷಿತ",
    adminDeck: "ಅಡ್ಮಿನ್ ಕಂಟ್ರೋಲ್ ಡೆಸ್ಕ್",
    adminDeckDesc: "ನೈಜ ಸಮಯದಲ್ಲಿ ಹೊಸ ಪ್ರೊಫೈಲ್‌ಗಳನ್ನು ಸೇರಿಸಿ ಅಥವಾ ತೆಗೆದುಹಾಕಿ.",
    addNewProfile: "ಹೊಸ ಪ್ರೊಫೈಲ್ ಸೇರಿಸಿ",
    totalProfiles: "ಒಟ್ಟು ಪ್ರೊಫೈಲ್‌ಗಳು",
    verifiedByAadhaar: "ಆಧಾರ್ ವೆರಿಫೈಡ್",
    sagotraCompliant: "ಸಗೋತ್ರ ವರ್ಜಿತ",
    activated: "ಸಕ್ರಿಯವಾಗಿದೆ",
    modTesting: "ಟೆಸ್ಟಿಂಗ್ ಸಾಮರ್ಥ್ಯ",
    differentRules: "ನಿಯಮಗಳು:",
    rulesDesc: "ಸೂಪರ್ ಅಡ್ಮಿನ್‌ಗೆ ಪ್ರೊಫೈಲ್ ಡಿಲೀಟ್ ಮಾಡಲು ಸಂಪೂರ್ಣ ಅಧಿಕಾರವಿದೆ.",
    age: "ವಯಸ್ಸು",
    gender: "ಲಿಂಗ",
    gotra: "ಗೋತ್ರ",
    sect: "ಪಂಗಡ",
    nakshatra: "ನಕ್ಷತ್ರ",
    rasi: "ಚಂದ್ರ ರಾಶಿ",
    lagnam: "ಜನ್ಮ ಲಗ್ನ",
    occupation: "ಉದ್ಯೋಗ",
    location: "ಸ್ಥಳ",
    education: "ಶಿಕ್ಷಣ",
    bio: "ಸ್ವವಿವರ",
    expectations: "ನಿರೀಕ್ಷೆಗಳು",
    achievements: "ಸಾಧನೆಗಳು",
    familyWishes: "ಕುಟುಂಬದ ಆಶಯಗಳು",
    viewHoroscope: "ಜಾತಕ ಚಾರ್ಟ್ ವೀಕ್ಷಿಸಿ",
    hideHoroscope: "ಜಾತಕ ಚಾರ್ಟ್ ಮರೆಮಾಡಿ",
    compatCalculator: "ಜೆಮಿನಿ ಹೊಂದಾಣಿಕೆ ಲೆಕ್ಕಾಚಾರ",
    startEncryptedChat: "ಸುರಕ್ಷಿತ ಚಾಟ್ ಪ್ರಾರಂಭಿಸಿ",
    aadhaarStatus: "ಆಧಾರ್ ಸ್ಕೋರ್",
    unverified: "ವೆರಿಫೈ ಆಗಿಲ್ಲ",
    verified: "ವೆರಿಫೈ ಆಗಿದೆ",
    yes: "ಹೌದು",
    no: "ಇಲ್ಲ",
    chevvaiDosham: "ಮಂಗಳ ದೋಷ (ಕುಜ)",
    rahuKetuDosham: "ರಾहु ಕೇತು ದೋಷ",
    backToMatches: "ವರ-ವಧು ಲಿಸ್ಟ್‌ಗೆ ಹಿಂತಿರುಗಿ",
    compatibilityChartTitle: "ಸಾಂಪ್ರದಾಯಿಕ ಕುಂಡಲಿ ಹೊಂದಾಣಿಕೆ",
    compatibilityChartDesc: "ವೇದಗಳ ಆಧಾರಿತ ಹೊಂದಾಣಿಕೆ ಲೆಕ್ಕಾಚಾರಗಳು ಮತ್ತು ಜೆಮಿನಿ ವಿಶ್ಲೇಷಣೆ.",
    lifestyleHarmony: "ಜೀವನಶೈಲಿ ಸಾಮರಸ್ಯ",
    coreValuesAlign: "ಮೌಲ್ಯಗಳ ಹೊಂದಾಣಿಕೆ",
    careerSynergy: "ಉದ್ಯೋಗ ಹೊಂದಾಣಿಕೆ",
    emotionalConnect: "ಭಾವನಾತ್ಮಕ ಸಂಪರ್ಕ",
    overallScore: "ಒಟ್ಟು ಸ್ಕೋರ್",
    geminiInsight: "ಜೆಮಿನಿ ಕೃತಕ ಬುದ್ಧಿಮತ್ತೆ ಹೊಂದಾಣಿಕೆ ನೋಟ",
    secureChatTitle: "ಸುರಕ್ಷಿತ ಚಾಟ್",
    secureChatDesc: "ಎಂಡ್-ಟು-ಎಂಡ್ ಗೂಢಲಿಪೀಕರಣ ರಕ್ಷಣೆ",
    ciphertext: "ಗೂಢಲಿಪಿ (Ciphertext)",
    decryptedText: "ಡೀಕ್ರಿಪ್ಟ್ ಆದ ಪಠ್ಯ",
    typeAMessage: "ಸುರಕ್ಷಿತ ಸಂದೇಶ ಟೈಪ್ ಮಾಡಿ...",
    send: "ಕಳುಹಿಸಿ",
    sacredVirtualMeeting: "Pvitr వర్చువల్ మీటింగ్",
    meetingDesc: "ಸುರಕ್ಷಿತ ವೀಡಿಯೊ ಸಂಪರ್ಕದೊಂದಿಗೆ ಮುಖಾಮುಖಿ ಕುಟುಂಬ ಸಂವಾದ.",
    p2pStatus: "ವೀಡಿಯೊ ಕನೆಕ್ಷನ್ ಸ್ಟೇಟಸ್",
    startSafeCall: "ವೀಡಿಯೊ ಕರೆ ಆರಂಭಿಸಿ",
    disconnectCall: "ಕರೆ ಕಡಿತಗೊಳಿಸಿ",
    kalyanaVendors: "ಕಲ್ಯಾಣ ಸೇವೆಗಳು",
    vendorsDesc: "ಸಾತ್ವಿಕ ಅಡುಗೆ ಸೇವೆಗಳು, ಪುರೋಹಿತರು, ಕಲ್ಯಾಣ ಮಂಟಪಗಳು ಮತ್ತು ಜ್ಯೋತಿಷಿಗಳು.",
    bookNow: "ಬುಕ್ ಮಾಡಿ",
    rating: "ರೇಟಿಂಗ್",
    pricing: "ಬೆಲೆ ಮಾಹಿತಿ",
    contactPerson: "ಸಂಪರ್ಕ ಅಧಿಕಾರಿ",
    verificationDesk: "ಬ್ರಾಹ್ಮಣ ವೆರಿಫಿಕೇಶನ್ ಡೆಸ್ಕ್",
    verificationDesc: "ಆಧಾರ್ ಮತ್ತು ನಕ್ಷತ್ರ ವಿವರಗಳ ವೆರಿಫಿಕೇಶನ್ ಪರಿಶೀಲನೆ.",
    auditLog: "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಆಡಿಟ್ ಲಾಗ್",
    auditLogDesc: "ಸಿಸ್ಟಮ್ ಲಾಗಿನ್ ಮತ್ತು ಆಡಳಿತಾತ್ಮక ಮಾಹಿತಿಯ ಲಾಗ್ ರೆಕಾರ್ಡ್ಸ್.",
  },
  te: {
    title: "HERITAGE MATRIMONY",
    subtitle: "పవిత్ర వంశం • బ్రాహ్మణ కూటమి",
    matches: "వర-వధువులు",
    compatibility: "జాతక పొంతన",
    chat: "సురక్షిత చాట్",
    videoCall: "వీడియో కాల్",
    vendorsHub: "ఆన్‌లైన్ స్టోర్",
    verifyHub: "ధృవీకరణ కేంద్రం",
    selfAudit: "సిస్టమ్ ఆడిట్",
    font: "అక్షర పరిమాణం",
    verifyId: "ధృవీకరణ",
    aadhaarVerified: "ఆధార్ ధృవీకరించబడింది",
    memberView: "సభ్యుల వీక్షణ",
    superAdmin: "సూపర్ అడ్మిన్",
    moderator: "మోడరేటర్",
    support: "సపోర్ట్",
    traditionalFilters: "సాంప్రదాయ వడపోతలు",
    traditionalFiltersDesc: "గోత్రము, జన్మ నక్షత్రం మరియు రాశి ఆధారంగా శోధించండి.",
    allGenders: "అన్ని లింగాలు",
    allBrahminSects: "అన్ని బ్రాహ్మణ శాఖలు",
    allAncestralGotras: "అన్ని గోత్రాలు",
    seekingMen: "వరుని అన్వేషణ (వధువు)",
    seekingWomen: "వధువు అన్వేషణ (వరుడు)",
    shubhVivaah: "శుభ వివాహం మరియు గోత్ర పవిత్రత",
    agraharamUnion: "మంగళకర అగ్రహార పొంతన",
    bannerDesc: "బ్రాహ్మణ సమాజం కోసం ప్రత్యేకంగా రూపొందించిన హెరిటేజ్ మ్యాట్రిమోనికి స్వాగతం. గోత్ర అనుకూలత, జాతక విశ్లేషణను తనిఖీ చేయండి.",
    verifiedSects: "ధృవీకరించబడిన శాఖలు",
    gotraIntegrity: "గోత్ర నిబద్ధత",
    secure100: "100% సురక్షితం",
    adminDeck: "అడ్మిన్ కంట్రోల్ డెస్క్",
    adminDeckDesc: "ప్రొఫైల్స్ ని చేర్చడం లేదా తొలగించడం లాంటి అడ్మిన్ పనుల పరీక్ష చేయండి.",
    addNewProfile: "కొత్త ప్రొఫైల్ చేర్చు",
    totalProfiles: "మొత్తం ప్రొఫైల్స్",
    verifiedByAadhaar: "ఆధార్ ధృవీకరించబడినవి",
    sagotraCompliant: "సగోత్ర నిషేధం",
    activated: "క్రియాశీలకంగా ఉంది",
    modTesting: "పరీక్షా సామర్థ్యం",
    differentRules: "నియమాలు:",
    rulesDesc: "ప్రొఫైల్స్ తొలగించడానికి సూపర్ అడ్మిన్‌కు పూర్తి అధికారం ఉంది.",
    age: "వయస్సు",
    gender: "లింగం",
    gotra: "గోత్రం",
    sect: "శాఖ",
    nakshatra: "నक्षत्रం",
    rasi: "చంద్ర రాశి",
    lagnam: "జన్మ లగ్నం",
    occupation: "ఉద్యోగం",
    location: "ప్రదేశం",
    education: "విద్య",
    bio: "పరిచయం",
    expectations: "నిరీక్షణలు",
    achievements: "విజయాలు",
    familyWishes: "కుటుంబ అభిలాషలు",
    viewHoroscope: "జాతక చక్రం చూడండి",
    hideHoroscope: "జాతక చక్రం దాచండి",
    compatCalculator: "జెమిని జాతక పొంతన గణన",
    startEncryptedChat: "సురక్షిత చాట్ ప్రారంభించండి",
    aadhaarStatus: "ఆధార్ స్కోరు",
    unverified: "ధృవీకరించబడలేదు",
    verified: "ధృవీకరించబడింది",
    yes: "అవును",
    no: "కాదు",
    chevvaiDosham: "కుజ దోషం",
    rahuKetuDosham: "రాహు కేతు దోషం",
    backToMatches: "మరల మ్యాచ్‌ల జాబితాకు",
    compatibilityChartTitle: "సాంప్రదాయ కుండలి పొంతన",
    compatibilityChartDesc: "వేద ఆధారిత పొంతనల లెక్కలు మరియు జెమిని అనుకూలత విశ్లేషణ.",
    lifestyleHarmony: "జీవనశైలి సామరస్యం",
    coreValuesAlign: "విలువల పొంతన",
    careerSynergy: "ఉద్యోగ సానుకూलత",
    emotionalConnect: "భావోద్వేగ బంధం",
    overallScore: "మొత్తం స్కోరు",
    geminiInsight: "జెమిని కృత్రిమ మేధస్సు పొంతన వీక్షణ",
    secureChatTitle: "సురక్షిత చాట్",
    secureChatDesc: "ఎండ్-トゥ-ఎండ్ గూఢలిపిక రక్షణ",
    ciphertext: "రహస్య లిపి (Ciphertext)",
    decryptedText: "డీక్రిప్ట్ చేసిన సందేశం",
    typeAMessage: "సురక్షిత సందేశాన్ని టైప్ చేయండి...",
    send: "పంపించు",
    sacredVirtualMeeting: "పవిత్ర వర్చువల్ సమావేశం",
    meetingDesc: "సురక్షిత వీడియో కనెక్షన్‌తో ముఖాముఖి కుటుంబ సంభాషణ.",
    p2pStatus: "వీడియో కనెక్షన్ స్థితి",
    startSafeCall: "వీడియో కాల్ ప్రారంభించు",
    disconnectCall: "కాల్ ముగించు",
    kalyanaVendors: "కళ్యాణ సేవలు",
    vendorsDesc: "సాత్విక వంట సేవలు, పురోహితులు, కళ్యాణ మండపాలు మరియు సిద్ధాంతులు.",
    bookNow: "బుక్ చేయండి",
    rating: "రేటింగ్",
    pricing: "ధరల సమాచారం",
    contactPerson: "సంప్రదించాల్సిన వ్యక్తి",
    verificationDesk: "బ్రాహ్మణ వెరిఫికೇಶన్ డెస్క్",
    verificationDesc: "ఆధార్ మరియు నక్షత్ర వివరాల వెరిఫికೇಶన్ పరిశీలన.",
    auditLog: "ప్లాట్‌ఫార్మ్ ఆడిట్ లాగ్",
    auditLogDesc: "సిస్టమ్ సెక్యూరిటీ లాగ్స్ మరియు అడ్మిన్ చర్యల రికార్డ్స్.",
  },
  ta: {
    title: "HERITAGE MATRIMONY",
    subtitle: "புனித குலம் • பிராமணர் வரன்",
    matches: "பொருத்தங்கள்",
    compatibility: "ஜாதக பொருத்தம்",
    chat: "பாதுகாப்பான அரட்டை",
    videoCall: "வீடியோ கால்",
    vendorsHub: "ஆன்லைன் ஸ்டோர்",
    verifyHub: "சரிபார்ப்பு மையம்",
    selfAudit: "கணினி தணிக்கை",
    font: "எழுத்து அளவு",
    verifyId: "சரிபார்ப்பு ஐடி",
    aadhaarVerified: "ஆதார் சரிபார்க்கப்பட்டது",
    memberView: "உறுப்பினர் பார்வை",
    superAdmin: "சூப்பர் அட்மின்",
    moderator: "மதிப்பீட்டாளர்",
    support: "ஆதரவு குழு",
    traditionalFilters: "பாரம்பரிய வடிகட்டிகள்",
    traditionalFiltersDesc: "கோத்திரம், நட்சத்திரம் மற்றும் ராசியின் அடிப்படையில் தேடுங்கள்.",
    allGenders: "அனைத்து பாலினங்கள்",
    allBrahminSects: "அனைத்து பிராமண உட்பிரிவுகள்",
    allAncestralGotras: "அனைத்து கோத்திரங்கள்",
    seekingMen: "வரன் தேடும் பெண் (பெண்)",
    seekingWomen: "பெண் தேடும் வரன் (ஆண்)",
    shubhVivaah: "சுப விவாஹம் மற்றும் கோத்திர சுத்தம்",
    agraharamUnion: "மங்களகர அக்ரகார பொருத்தம்",
    bannerDesc: "பிராமண சமூகத்திற்காக பிரத்யேகமாக வடிவமைக்கப்பட்ட ஹெரிடேஜ் மேட்ரிமோனிக்கு வரவேற்கிறோம். கோத்திர பொருத்தம் மற்றும் ஜாதக கணிப்புகளை சரிபார்க்கவும்.",
    verifiedSects: "சரிபார்க்கப்பட்ட உட்பிரிவுகள்",
    gotraIntegrity: "கோத்திர சுத்தம்",
    secure100: "100% பாதுகாப்பானது",
    adminDeck: "அட்மின் கட்டுப்பாட்டு பலகை",
    adminDeckDesc: "புதிய சோதனை கணக்குகளை உருவாக்குதல் மற்றும் நீக்குதல் போன்ற அட்மின் சோதனைகளை செய்யுங்கள்.",
    addNewProfile: "புதிய சோதனை கணக்கை சேர்",
    totalProfiles: "மொத்த கணக்குகள்",
    verifiedByAadhaar: "ஆதார் சரிபார்க்கப்பட்டவை",
    sagotraCompliant: "சகோத்திர தடை",
    activated: "செயலில் உள்ளது",
    modTesting: "சோதனை திறன்",
    differentRules: "விதிமுறைகள்:",
    rulesDesc: "சோதனை கணக்குகளை நீக்க சூப்பர் அட்மினுக்கு முழு அதிகாரம் உள்ளது.",
    age: "வயது",
    gender: "பாலினம்",
    gotra: "கோத்திரம்",
    sect: "உட்பிரிவு",
    nakshatra: "நட்சத்திரம்",
    rasi: "சந்திர ராசி",
    lagnam: "லக்னம்",
    occupation: "வேலை",
    location: "இருப்பிடம்",
    education: "படிப்பு",
    bio: "சுயவிவரம்",
    expectations: "எதிர்பார்ப்புகள்",
    achievements: "சாதனைகள்",
    familyWishes: "குடும்பத்தின் விருப்பம்",
    viewHoroscope: "ஜாதக கட்டத்தை காட்டு",
    hideHoroscope: "ஜாதக கட்டத்தை மறை",
    compatCalculator: "ஜெமினி ஜாதக பொருத்தம் காண்",
    startEncryptedChat: "பாதுகாப்பான அரட்டையை துவங்கு",
    aadhaarStatus: "ஆதார் பொருத்தம்",
    unverified: "சரிபார்க்கப்படவில்லை",
    verified: "சரிபார்க்கப்பட்டது",
    yes: "ஆம்",
    no: "இல்லை",
    chevvaiDosham: "செவ்வாய் தோஷம்",
    rahuKetuDosham: "ராகு கேது தோஷம்",
    backToMatches: "மீண்டும் வரன் பட்டியலுக்கு",
    compatibilityChartTitle: "பாரம்பரிய ஜாதக பொருத்தம்",
    compatibilityChartDesc: "வேத கணிப்புகள் மற்றும் ஜெமினி செயற்கை நுண்ணறிவு பகுப்பாய்வு.",
    lifestyleHarmony: "வாழ்க்கை முறை பொருத்தம்",
    coreValuesAlign: "கொள்கை பொருத்தம்",
    careerSynergy: "தொழில் பொருத்தம்",
    emotionalConnect: "உணர்ச்சி ரீதியான இணைப்பு",
    overallScore: "ஒட்டுமொத்த பொருத்தம்",
    geminiInsight: "ஜெமினி செயற்கை நுண்ணறிவின் முடிவு",
    secureChatTitle: "பாதுகாப்பான அரட்டை",
    secureChatDesc: "முழுமையாக குறியாக்கம் செய்யப்பட்ட அரட்டை பாதுகாப்பு",
    ciphertext: "மறைக்கப்பட்ட செய்தி (Ciphertext)",
    decryptedText: "வெளிப்படுத்தப்பட்ட செய்தி",
    typeAMessage: "பாதுகாப்பான செய்தியை தட்டச்சு செய்க...",
    send: "அனுப்பு",
    sacredVirtualMeeting: "புனித மெய்நிகர் சந்திப்பு",
    meetingDesc: "பாதுகாப்பான வீடியோ இணைப்புடன் கூடிய முகநூல் குடும்ப சந்திப்பு.",
    p2pStatus: "வீடியோ இணைப்பு நிலை",
    startSafeCall: "அழைப்பை துவங்கு",
    disconnectCall: "அழைப்பை துண்டி",
    kalyanaVendors: "கல்யாண வண்டர்கள்",
    vendorsDesc: "சாத்வீக சமையல், வைதீக புரோகிதர்கள், கல்யாண மண்டபங்கள் மற்றும் ஜோதிடர்கள்.",
    bookNow: "இப்போதே முன்பதிவு செய்க",
    rating: "மதிப்பீடு",
    pricing: "கட்டண விவரம்",
    contactPerson: "தொடர்பு கொள்ள வேண்டிய நபர்",
    verificationDesk: "பிராமண சரிபார்ப்பு மையம்",
    verificationDesc: "ஆதார் மற்றும் ஜாதக விவரங்களின் உண்மைத்தன்மை சோதனை.",
    auditLog: "மேடை தணிக்கை பதிவு",
    auditLogDesc: "கணினி பாதுகாப்பு மற்றும் அட்மின் பதிவுகளின் நேரடி கண்காணிப்பு.",
  },
  mr: {
    title: "HERITAGE MATRIMONY",
    subtitle: "पवित्र वंश • ब्राह्मण युती",
    matches: "योग्य स्थळे",
    compatibility: "पत्रिका मिलन",
    chat: "सुरक्षित चॅट",
    videoCall: "व्हिडिओ कॉल",
    vendorsHub: "ऑनलाइन स्टोअर",
    verifyHub: "पडताळणी केंद्र",
    selfAudit: "सिस्टम ऑडिट",
    font: "अक्षर आकार",
    verifyId: "ओळख सत्यापित करा",
    aadhaarVerified: "आधार सत्यापित",
    memberView: "सदस्य दृश्य",
    superAdmin: "मुख्य प्रशासक",
    moderator: "मध्यस्थ",
    support: "मदत कक्ष",
    traditionalFilters: "पारंपारिक वैवाहिक फिल्टर्स",
    traditionalFiltersDesc: "पूर्वजांचे गोत्र आणि नक्षत्रानुसार शोध घ्या.",
    allGenders: "सर्व लिंग",
    allBrahminSects: "सर्व ब्राह्मण संप्रदाय",
    allAncestralGotras: "सर्व गोत्र",
    seekingMen: "वर शोधत आहे (वधू)",
    seekingWomen: "वधू शोधत आहे (वर)",
    shubhVivaah: "शुभ विवाह आणि गोत्र पवित्रता",
    agraharamUnion: "मंगल अग्रहारम मिलन",
    bannerDesc: "धरोहर वैवाहिक मध्ये आपले स्वागत आहे, जे विशेषतः ब्राह्मण परिवारांसाठी आहे. पवित्र गोत्र अनुकूलता, जेमिनी पत्रिका विश्लेषण आणि आधार रेकॉर्ड तपासा.",
    verifiedSects: "सत्यापित संप्रदाय",
    gotraIntegrity: "गोत्र शुद्धता",
    secure100: "१००% सुरक्षित",
    adminDeck: "प्रशासक नियंत्रण पॅनेल",
    adminDeckDesc: "सिस्टम सुविधेचे परीक्षण करा, नवीन डमी प्रोफाइल जोडा किंवा काढून टाका.",
    addNewProfile: "नवीन मॉक प्रोफाइल जोडा",
    totalProfiles: "एकूण प्रोफाइल",
    verifiedByAadhaar: "आधार सत्यापित प्रोफाइल",
    sagotraCompliant: "सगोत्र निषेध",
    activated: "सक्रिय आहे",
    modTesting: "चाचणी क्षमता",
    differentRules: "नियम आणि अधिकार:",
    rulesDesc: "मुख्य प्रशासकाकडे प्रोफाइल हटवण्याचे पूर्ण अधिकार आहेत.",
    age: "वय",
    gender: "लिंग",
    gotra: "गोत्र",
    sect: "संप्रदाय",
    nakshatra: "नक्षत्र",
    rasi: "चंद्र राशी",
    lagnam: "जन्म लग्न",
    occupation: "व्यवसाय",
    location: "स्थान",
    education: "शिक्षण",
    bio: "परिचय",
    expectations: "अपेक्षा",
    achievements: "यशस्वी कामगिरी",
    familyWishes: "कौटुंबिक सदिच्छा",
    viewHoroscope: "कुंडली तक्ता पहा",
    hideHoroscope: "कुंडली लपवा",
    compatCalculator: "जेमिनी कुंडली मिलन करा",
    startEncryptedChat: "सुरक्षित चॅट सुरू करा",
    aadhaarStatus: "आधार जुळणी स्कोअर",
    unverified: "असत्यापित",
    verified: "सत्यापित",
    yes: "होय",
    no: "नाही",
    chevvaiDosham: "मंगळ दोष",
    rahuKetuDosham: "राहु-केतू दोष",
    backToMatches: "परत स्थळांच्या यादीवर",
    compatibilityChartTitle: "पारंपारिक अष्टकूट मिलन",
    compatibilityChartDesc: "वैदिक गणना आणि जेमिनी एआय विश्लेषणावर आधारित जुळणी.",
    lifestyleHarmony: "जीवनशैली सुसंवाद",
    coreValuesAlign: "मूलभूत विचार जुळणी",
    careerSynergy: "करिअर सुसंगतता",
    emotionalConnect: "भावनिक नाते",
    overallScore: "एकूण गुण",
    geminiInsight: "जेमिनी एआय निष्कर्ष",
    secureChatTitle: "सुरक्षित पीअर-टू-पीयर चॅट",
    secureChatDesc: "पूर्ण सुरक्षित कूटबद्ध चॅट कवच",
    ciphertext: "कूटबद्ध संदेश (सुरक्षित)",
    decryptedText: "वाचता येणारा संदेश",
    typeAMessage: "सुरक्षित संदेश टाईप करा...",
    send: "पाठवा",
    sacredVirtualMeeting: "पवित्र व्हर्च्युअल भेट",
    meetingDesc: "सुरक्षित आणि कूटबद्ध व्हिडिओ संवाद याद्वारे समोरासमोर कौटुंबिक मिलन.",
    p2pStatus: "कनेक्शन स्थिती",
    startSafeCall: "कॉल सुरू करा",
    disconnectCall: "कॉल संपवा",
    kalyanaVendors: "पवित्र विवाह वेंडर्स",
    vendorsDesc: "सात्विक केटरर्स, पूजनीय पुरोहित, मंगल कार्यालय आणि वैदिक ज्योतिषी.",
    bookNow: "आता बुक करा",
    rating: "रेटिंग",
    pricing: "दर माहिती",
    contactPerson: "संपर्क व्यक्ती",
    verificationDesk: "ब्राह्मण पडताळणी डेस्क",
    verificationDesc: "आधार तपशील आणि कुंडली प्रमाणपत्रांची पडताळणी.",
    auditLog: "प्लॅटफॉर्म ऑडिट लॉग",
    auditLogDesc: "सुरक्षा तपासणी, लॉगिन आणि प्रशासकीय बदलांचे थेट रेकॉर्ड्स.",
  }
};

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations["en"]) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("heritage_language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("heritage_language", language);
  }, [language]);

  const t = (key: keyof typeof translations["en"]): string => {
    if (key === "title") return "HERITAGE MATRIMONY";
    if (key === "subtitle") return "Sacred Lineage • Brahmin Alliance";
    const currentTranslations = translations[language] || translations["en"];
    return (currentTranslations[key] as string) || (translations["en"][key] as string) || String(key);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
